// Từ vựng TOEIC bổ sung (cùng định dạng với TOEIC_VOCAB trong data.js).
// File này nạp sau data.js và gộp mọi bộ từ thành VOCAB.

// Thêm từ vào các chủ đề đã có (khóa = id chủ đề)
const TOEIC_EXTRA = {
  office: [
    ['department', '/dɪˈpɑːtmənt/', 'n', 'phòng, ban', 'She works in the sales department.', 'division, section',
      [['sales department', 'phòng kinh doanh'], ['head of department', 'trưởng phòng']]],
    ['headquarters', '/ˌhedˈkwɔːtəz/', 'n', 'trụ sở chính', 'Our headquarters is in Ho Chi Minh City.', 'head office, main office',
      [['company headquarters', 'trụ sở công ty'], ['based at headquarters', 'làm việc tại trụ sở']]],
    ['branch', '/brɑːntʃ/', 'n', 'chi nhánh', 'The bank opened a new branch downtown.', 'office, division',
      [['branch office', 'văn phòng chi nhánh'], ['open a branch', 'mở chi nhánh']]],
    ['memo', '/ˈmeməʊ/', 'n', 'thông báo nội bộ', 'The manager sent a memo to all staff.', 'note, notice',
      [['send a memo', 'gửi thông báo nội bộ'], ['internal memo', 'bản ghi nhớ nội bộ']]],
    ['document', '/ˈdɒkjumənt/', 'n', 'tài liệu, văn bản', 'Please sign the document.', 'file, paper',
      [['sign a document', 'ký văn bản'], ['official document', 'văn bản chính thức']]],
    ['equipment', '/ɪˈkwɪpmənt/', 'n', 'thiết bị', 'The office needs new equipment.', 'devices, tools',
      [['office equipment', 'thiết bị văn phòng'], ['piece of equipment', 'một món thiết bị']]],
    ['overtime', '/ˈəʊvətaɪm/', 'n', 'giờ làm thêm', 'I worked overtime last week.', 'extra hours',
      [['work overtime', 'làm thêm giờ'], ['overtime pay', 'tiền làm thêm giờ']]],
    ['shift', '/ʃɪft/', 'n', 'ca làm việc', 'He works the night shift.', 'work period, turn',
      [['night shift', 'ca đêm'], ['work a shift', 'làm một ca']]],
    ['workload', '/ˈwɜːkləʊd/', 'n', 'khối lượng công việc', 'My workload is very heavy this month.', 'amount of work',
      [['heavy workload', 'khối lượng công việc nặng'], ['reduce the workload', 'giảm khối lượng công việc']]],
    ['handle', '/ˈhændl/', 'v', 'xử lý, giải quyết', 'She handles all customer complaints.', 'deal with, manage',
      [['handle a complaint', 'xử lý khiếu nại'], ['handle a situation', 'xử lý tình huống']]],
    ['review', '/rɪˈvjuː/', 'v/n', 'xem xét, đánh giá', 'Please review the report before the meeting.', 'examine, check',
      [['review a document', 'xem lại tài liệu'], ['performance review', 'buổi đánh giá hiệu suất']]],
    ['remind', '/rɪˈmaɪnd/', 'v', 'nhắc nhở', 'Please remind me to call the client.', 'prompt, tell',
      [['remind somebody to', 'nhắc ai làm gì'], ['remind somebody about', 'nhắc ai về việc gì']]],
    ['arrange', '/əˈreɪndʒ/', 'v', 'sắp xếp, thu xếp', 'I will arrange a meeting with the client.', 'organize, set up',
      [['arrange a meeting', 'sắp xếp cuộc họp'], ['arrange for', 'thu xếp cho']]],
    ['temporary', '/ˈtemprəri/', 'adj', 'tạm thời', 'We hired temporary staff for the holiday.', 'short-term, interim',
      [['temporary staff', 'nhân viên thời vụ'], ['temporary solution', 'giải pháp tạm thời']]],
    ['productivity', '/ˌprɒdʌkˈtɪvəti/', 'n', 'năng suất', 'The new software improved productivity.', 'efficiency, output',
      [['increase productivity', 'tăng năng suất'], ['low productivity', 'năng suất thấp']]],
  ],
  hr: [
    ['recruit', '/rɪˈkruːt/', 'v', 'tuyển dụng', 'We are recruiting new engineers.', 'hire, employ',
      [['recruit staff', 'tuyển nhân viên'], ['recruitment agency', 'công ty tuyển dụng']]],
    ['interview', '/ˈɪntəvjuː/', 'n/v', 'phỏng vấn', 'I have a job interview tomorrow.', 'meeting, consultation',
      [['job interview', 'phỏng vấn xin việc'], ['conduct an interview', 'tiến hành phỏng vấn']]],
    ['candidate', '/ˈkændɪdət/', 'n', 'ứng viên', 'She is the best candidate for the job.', 'applicant, nominee',
      [['ideal candidate', 'ứng viên lý tưởng'], ['shortlist candidates', 'lọc danh sách ứng viên vòng trong']]],
    ['employee', '/ɪmˈplɔɪiː/', 'n', 'nhân viên', 'The company has five hundred employees.', 'worker, staff member',
      [['full-time employee', 'nhân viên toàn thời gian'], ['employee training', 'đào tạo nhân viên']]],
    ['employer', '/ɪmˈplɔɪə(r)/', 'n', 'người sử dụng lao động', 'My employer pays for my training.', 'company, boss',
      [['former employer', 'chủ cũ'], ['potential employer', 'nhà tuyển dụng tiềm năng']]],
    ['personnel', '/ˌpɜːsəˈnel/', 'n', 'nhân sự', 'All personnel must wear ID badges.', 'staff, workforce',
      [['personnel department', 'phòng nhân sự'], ['medical personnel', 'nhân viên y tế']]],
    ['training', '/ˈtreɪnɪŋ/', 'n', 'sự đào tạo', 'New staff receive two weeks of training.', 'instruction, coaching',
      [['training session', 'buổi đào tạo'], ['receive training', 'được đào tạo']]],
    ['retire', '/rɪˈtaɪə(r)/', 'v', 'nghỉ hưu', 'My father retired last year.', 'stop working, step down',
      [['retire from', 'nghỉ hưu từ'], ['retirement party', 'tiệc chia tay nghỉ hưu']]],
    ['dismiss', '/dɪsˈmɪs/', 'v', 'sa thải; gạt bỏ', 'He was dismissed for being late too often.', 'fire, let go',
      [['be dismissed from', 'bị sa thải khỏi'], ['dismiss an idea', 'gạt bỏ một ý kiến']]],
    ['performance', '/pəˈfɔːməns/', 'n', 'hiệu suất, thành tích', 'Her performance this year was excellent.', 'achievement, results',
      [['job performance', 'hiệu quả công việc'], ['improve performance', 'cải thiện hiệu suất']]],
    ['evaluate', '/ɪˈvæljueɪt/', 'v', 'đánh giá', 'Managers evaluate staff twice a year.', 'assess, judge',
      [['evaluate performance', 'đánh giá hiệu suất'], ['carefully evaluate', 'đánh giá cẩn thận']]],
    ['reference', '/ˈrefrəns/', 'n', 'thư giới thiệu; sự tham khảo', 'Please provide two references.', 'recommendation, referee',
      [['letter of reference', 'thư giới thiệu'], ['for future reference', 'để tham khảo sau này']]],
    ['internship', '/ˈɪntɜːnʃɪp/', 'n', 'kỳ thực tập', 'She did an internship at a bank.', 'placement, training period',
      [['do an internship', 'đi thực tập'], ['paid internship', 'thực tập có lương']]],
    ['orientation', '/ˌɔːriənˈteɪʃn/', 'n', 'buổi định hướng (nhân viên mới)', 'New employees attend an orientation on their first day.', 'introduction, induction',
      [['orientation session', 'buổi định hướng'], ['new employee orientation', 'định hướng nhân viên mới']]],
    ['workforce', '/ˈwɜːkfɔːs/', 'n', 'lực lượng lao động', 'The company plans to reduce its workforce.', 'staff, employees',
      [['skilled workforce', 'lao động có tay nghề'], ['reduce the workforce', 'cắt giảm nhân sự']]],
  ],
  marketing: [
    ['brand', '/brænd/', 'n', 'thương hiệu', 'This is a well-known brand.', 'label, trademark',
      [['brand name', 'tên thương hiệu'], ['brand awareness', 'độ nhận diện thương hiệu']]],
    ['campaign', '/kæmˈpeɪn/', 'n', 'chiến dịch', 'The new campaign was very successful.', 'promotion, drive',
      [['marketing campaign', 'chiến dịch tiếp thị'], ['launch a campaign', 'phát động chiến dịch']]],
    ['consumer', '/kənˈsjuːmə(r)/', 'n', 'người tiêu dùng', 'Consumers want cheaper products.', 'customer, buyer',
      [['consumer demand', 'nhu cầu tiêu dùng'], ['consumer behaviour', 'hành vi người tiêu dùng']]],
    ['strategy', '/ˈstrætədʒi/', 'n', 'chiến lược', 'We need a new marketing strategy.', 'plan, approach',
      [['develop a strategy', 'xây dựng chiến lược'], ['business strategy', 'chiến lược kinh doanh']]],
    ['trend', '/trend/', 'n', 'xu hướng', 'Online shopping is a growing trend.', 'tendency, pattern',
      [['current trend', 'xu hướng hiện tại'], ['follow a trend', 'chạy theo xu hướng']]],
    ['sample', '/ˈsɑːmpl/', 'n', 'hàng mẫu', 'We give free samples to customers.', 'specimen, example',
      [['free sample', 'hàng mẫu miễn phí'], ['product sample', 'mẫu sản phẩm']]],
    ['catalogue', '/ˈkætəlɒɡ/', 'n', 'danh mục sản phẩm', 'Please check our new catalogue.', 'list, brochure',
      [['product catalogue', 'danh mục sản phẩm'], ['online catalogue', 'danh mục trực tuyến']]],
    ['feature', '/ˈfiːtʃə(r)/', 'n/v', 'tính năng; có đặc điểm', 'The phone has many new features.', 'characteristic, function',
      [['key feature', 'tính năng chính'], ['new feature', 'tính năng mới']]],
    ['quality', '/ˈkwɒləti/', 'n', 'chất lượng', 'We never compromise on quality.', 'standard, grade',
      [['high quality', 'chất lượng cao'], ['quality control', 'kiểm soát chất lượng']]],
    ['reputation', '/ˌrepjuˈteɪʃn/', 'n', 'danh tiếng', 'The company has a good reputation.', 'image, name',
      [['good reputation', 'danh tiếng tốt'], ['build a reputation', 'xây dựng danh tiếng']]],
    ['retail', '/ˈriːteɪl/', 'n/adj', 'bán lẻ', 'She works in retail.', 'selling, sales',
      [['retail store', 'cửa hàng bán lẻ'], ['retail price', 'giá bán lẻ']]],
    ['wholesale', '/ˈhəʊlseɪl/', 'n/adj', 'bán buôn, bán sỉ', 'We buy our products wholesale.', 'bulk selling',
      [['wholesale price', 'giá sỉ'], ['wholesale market', 'chợ đầu mối']]],
    ['merchandise', '/ˈmɜːtʃəndaɪs/', 'n', 'hàng hóa', 'All merchandise is on sale this week.', 'goods, products',
      [['display merchandise', 'trưng bày hàng hóa'], ['return merchandise', 'trả lại hàng']]],
    ['brochure', '/ˈbrəʊʃə(r)/', 'n', 'tờ giới thiệu, tờ quảng cáo', 'Please take a brochure.', 'leaflet, pamphlet',
      [['travel brochure', 'tờ giới thiệu du lịch'], ['hand out brochures', 'phát tờ rơi']]],
    ['sponsor', '/ˈspɒnsə(r)/', 'v/n', 'tài trợ; nhà tài trợ', 'A bank sponsored the event.', 'fund, support',
      [['sponsor an event', 'tài trợ sự kiện'], ['main sponsor', 'nhà tài trợ chính']]],
  ],
  finance: [
    ['loan', '/ləʊn/', 'n', 'khoản vay', 'We took out a loan to buy a house.', 'credit, advance',
      [['take out a loan', 'vay tiền'], ['repay a loan', 'trả nợ vay']]],
    ['interest', '/ˈɪntrəst/', 'n', 'tiền lãi, lãi suất', 'The bank charges five percent interest.', 'charge, return',
      [['interest rate', 'lãi suất'], ['pay interest', 'trả lãi']]],
    ['balance', '/ˈbæləns/', 'n', 'số dư', 'Please check your account balance.', 'remainder, total',
      [['account balance', 'số dư tài khoản'], ['outstanding balance', 'số tiền còn nợ']]],
    ['deposit', '/dɪˈpɒzɪt/', 'n/v', 'tiền đặt cọc; gửi tiền', 'You need to pay a deposit.', 'down payment, advance',
      [['pay a deposit', 'đặt cọc'], ['make a deposit', 'gửi tiền vào tài khoản']]],
    ['withdraw', '/wɪðˈdrɔː/', 'v', 'rút (tiền)', 'I want to withdraw some cash.', 'take out, remove',
      [['withdraw money', 'rút tiền'], ['withdraw from an account', 'rút tiền từ tài khoản']]],
    ['transaction', '/trænˈzækʃn/', 'n', 'giao dịch', 'The transaction was completed online.', 'deal, exchange',
      [['online transaction', 'giao dịch trực tuyến'], ['complete a transaction', 'hoàn tất giao dịch']]],
    ['tax', '/tæks/', 'n', 'thuế', 'Prices include tax.', 'duty, levy',
      [['pay tax', 'nộp thuế'], ['income tax', 'thuế thu nhập']]],
    ['audit', '/ˈɔːdɪt/', 'n/v', 'kiểm toán', 'The company has an audit every year.', 'inspection, review',
      [['conduct an audit', 'thực hiện kiểm toán'], ['financial audit', 'kiểm toán tài chính']]],
    ['asset', '/ˈæset/', 'n', 'tài sản', 'Our staff are our greatest asset.', 'property, resource',
      [['valuable asset', 'tài sản quý giá'], ['company assets', 'tài sản công ty']]],
    ['debt', '/det/', 'n', 'khoản nợ', 'They paid off all their debts.', 'loan, liability',
      [['pay off a debt', 'trả hết nợ'], ['in debt', 'đang mắc nợ']]],
    ['payment', '/ˈpeɪmənt/', 'n', 'sự thanh toán', 'We accept payment by credit card.', 'settlement, fee',
      [['make a payment', 'thanh toán'], ['payment method', 'phương thức thanh toán']]],
    ['receipt', '/rɪˈsiːt/', 'n', 'biên lai', 'Please keep your receipt.', 'proof of purchase, voucher',
      [['keep a receipt', 'giữ biên lai'], ['issue a receipt', 'xuất biên lai']]],
    ['accountant', '/əˈkaʊntənt/', 'n', 'kế toán viên', 'Our accountant prepares the tax forms.', 'bookkeeper, auditor',
      [['chief accountant', 'kế toán trưởng'], ['hire an accountant', 'thuê kế toán']]],
    ['quarter', '/ˈkwɔːtə(r)/', 'n', 'quý (3 tháng)', 'Sales rose in the second quarter.', 'three-month period',
      [['first quarter', 'quý một'], ['quarterly report', 'báo cáo quý']]],
    ['afford', '/əˈfɔːd/', 'v', 'có đủ khả năng chi trả', 'We cannot afford a new office.', 'pay for, manage',
      [['can afford', 'đủ tiền để'], ['affordable price', 'giá phải chăng']]],
  ],
  travel: [
    ['passenger', '/ˈpæsɪndʒə(r)/', 'n', 'hành khách', 'All passengers must show their tickets.', 'traveller, rider',
      [['passenger seat', 'ghế hành khách'], ['passengers on board', 'hành khách trên tàu/xe']]],
    ['flight', '/flaɪt/', 'n', 'chuyến bay', 'My flight leaves at six.', 'trip, air journey',
      [['book a flight', 'đặt vé máy bay'], ['connecting flight', 'chuyến bay nối chuyến']]],
    ['arrival', '/əˈraɪvl/', 'n', 'sự đến nơi', 'Please call me on arrival.', 'coming, landing',
      [['arrival time', 'giờ đến'], ['on arrival', 'khi đến nơi']]],
    ['terminal', '/ˈtɜːmɪnl/', 'n', 'nhà ga (sân bay, bến xe)', 'Our flight leaves from Terminal 2.', 'station, building',
      [['airport terminal', 'nhà ga sân bay'], ['bus terminal', 'bến xe buýt']]],
    ['gate', '/ɡeɪt/', 'n', 'cổng (lên máy bay)', 'Please go to Gate 5.', 'exit, entrance',
      [['boarding gate', 'cổng lên máy bay'], ['gate number', 'số cổng']]],
    ['customs', '/ˈkʌstəmz/', 'n', 'hải quan', 'We went through customs quickly.', 'border control',
      [['go through customs', 'làm thủ tục hải quan'], ['customs officer', 'nhân viên hải quan']]],
    ['passport', '/ˈpɑːspɔːt/', 'n', 'hộ chiếu', 'Please show your passport.', 'travel document, ID',
      [['valid passport', 'hộ chiếu còn hạn'], ['apply for a passport', 'làm hộ chiếu']]],
    ['visa', '/ˈviːzə/', 'n', 'thị thực', 'You need a visa to visit that country.', 'entry permit',
      [['apply for a visa', 'xin thị thực'], ['tourist visa', 'thị thực du lịch']]],
    ['commute', '/kəˈmjuːt/', 'v/n', 'đi làm (hằng ngày)', 'I commute to work by train.', 'travel, journey',
      [['commute to work', 'đi làm'], ['daily commute', 'quãng đường đi làm hằng ngày']]],
    ['route', '/ruːt/', 'n', 'tuyến đường', 'This is the fastest route to the airport.', 'way, path',
      [['bus route', 'tuyến xe buýt'], ['take a route', 'đi theo tuyến đường']]],
    ['transfer', '/trænsˈfɜː(r)/', 'v/n', 'chuyển; đưa đón', 'The hotel offers a free airport transfer.', 'move, shift',
      [['airport transfer', 'xe đưa đón sân bay'], ['transfer money', 'chuyển tiền']]],
    ['vehicle', '/ˈviːəkl/', 'n', 'phương tiện, xe', 'Please park your vehicle here.', 'car, transport',
      [['park a vehicle', 'đỗ xe'], ['company vehicle', 'xe công ty']]],
    ['round trip', '/ˌraʊnd ˈtrɪp/', 'n', 'chuyến khứ hồi', 'I bought a round trip ticket.', 'return journey',
      [['round trip ticket', 'vé khứ hồi'], ['round trip fare', 'giá vé khứ hồi']]],
    ['tour', '/tʊə(r)/', 'n/v', 'chuyến tham quan', 'We took a tour of the factory.', 'trip, visit',
      [['guided tour', 'chuyến tham quan có hướng dẫn'], ['tour guide', 'hướng dẫn viên']]],
    ['check-in', '/ˈtʃek ɪn/', 'n', 'thủ tục nhận phòng / lên máy bay', 'Check-in starts at two in the afternoon.', 'registration',
      [['check-in counter', 'quầy làm thủ tục'], ['online check-in', 'làm thủ tục trực tuyến']]],
  ],
  meeting: [
    ['discuss', '/dɪˈskʌs/', 'v', 'thảo luận (không đi với "about")', 'We need to discuss the budget.', 'talk about, debate',
      [['discuss a plan', 'thảo luận kế hoạch'], ['discuss in detail', 'thảo luận chi tiết']]],
    ['minutes', '/ˈmɪnɪts/', 'n', 'biên bản cuộc họp', 'Who will take the minutes?', 'notes, record',
      [['take the minutes', 'ghi biên bản'], ['meeting minutes', 'biên bản cuộc họp']]],
    ['participant', '/pɑːˈtɪsɪpənt/', 'n', 'người tham gia', 'Each participant will receive a certificate.', 'attendee, member',
      [['workshop participant', 'người dự hội thảo'], ['active participant', 'người tham gia tích cực']]],
    ['summarize', '/ˈsʌməraɪz/', 'v', 'tóm tắt', 'Let me summarize the main points.', 'sum up, outline',
      [['summarize the main points', 'tóm tắt ý chính'], ['briefly summarize', 'tóm tắt ngắn gọn']]],
    ['clarify', '/ˈklærəfaɪ/', 'v', 'làm rõ', 'Could you clarify your question?', 'explain, make clear',
      [['clarify a point', 'làm rõ một ý'], ['clarify the situation', 'làm rõ tình hình']]],
    ['consensus', '/kənˈsensəs/', 'n', 'sự đồng thuận', 'The team reached a consensus.', 'agreement, harmony',
      [['reach a consensus', 'đạt được đồng thuận'], ['general consensus', 'sự đồng thuận chung']]],
    ['opinion', '/əˈpɪnjən/', 'n', 'ý kiến', 'What is your opinion on this?', 'view, idea',
      [['in my opinion', 'theo ý tôi'], ['express an opinion', 'bày tỏ ý kiến']]],
    ['objective', '/əbˈdʒektɪv/', 'n', 'mục tiêu', 'Our main objective is to increase sales.', 'goal, aim',
      [['main objective', 'mục tiêu chính'], ['achieve an objective', 'đạt mục tiêu']]],
    ['workshop', '/ˈwɜːkʃɒp/', 'n', 'hội thảo thực hành', 'I attended a workshop on leadership.', 'seminar, class',
      [['hold a workshop', 'tổ chức hội thảo'], ['training workshop', 'hội thảo đào tạo']]],
    ['seminar', '/ˈsemɪnɑː(r)/', 'n', 'hội thảo chuyên đề', 'The seminar starts at nine.', 'conference, lecture',
      [['attend a seminar', 'dự hội thảo'], ['business seminar', 'hội thảo kinh doanh']]],
    ['reschedule', '/ˌriːˈʃedjuːl/', 'v', 'dời lịch', 'Can we reschedule the meeting?', 'postpone, rearrange',
      [['reschedule a meeting', 'dời lịch họp'], ['reschedule for', 'dời sang (thời điểm)']]],
    ['brainstorm', '/ˈbreɪnstɔːm/', 'v', 'cùng đưa ra ý tưởng', "Let's brainstorm some ideas.", 'think up, generate ideas',
      [['brainstorm ideas', 'cùng nghĩ ý tưởng'], ['brainstorming session', 'buổi động não']]],
    ['handout', '/ˈhændaʊt/', 'n', 'tài liệu phát tay', 'Please read the handout.', 'leaflet, printout',
      [['distribute handouts', 'phát tài liệu'], ['refer to the handout', 'xem tài liệu phát tay']]],
    ['respond', '/rɪˈspɒnd/', 'v', 'phản hồi, trả lời', 'Please respond by Friday.', 'reply, answer',
      [['respond to', 'trả lời, đáp lại'], ['respond quickly', 'phản hồi nhanh']]],
    ['convince', '/kənˈvɪns/', 'v', 'thuyết phục', 'She convinced the client to sign.', 'persuade, win over',
      [['convince somebody to', 'thuyết phục ai làm gì'], ['fully convinced', 'hoàn toàn bị thuyết phục']]],
  ],
  purchase: [
    ['quantity', '/ˈkwɒntəti/', 'n', 'số lượng', 'Please state the quantity you need.', 'amount, number',
      [['large quantity', 'số lượng lớn'], ['in large quantities', 'với số lượng lớn']]],
    ['item', '/ˈaɪtəm/', 'n', 'món hàng, mục', 'This item is out of stock.', 'product, article',
      [['sale item', 'hàng giảm giá'], ['item number', 'mã hàng']]],
    ['product', '/ˈprɒdʌkt/', 'n', 'sản phẩm', 'We sell over two hundred products.', 'goods, item',
      [['new product', 'sản phẩm mới'], ['product line', 'dòng sản phẩm']]],
    ['goods', '/ɡʊdz/', 'n', 'hàng hóa', 'The goods were delivered yesterday.', 'products, merchandise',
      [['damaged goods', 'hàng bị hư hỏng'], ['consumer goods', 'hàng tiêu dùng']]],
    ['stock', '/stɒk/', 'n', 'hàng trong kho', 'We have plenty of stock.', 'inventory, supply',
      [['in stock', 'còn hàng'], ['out of stock', 'hết hàng']]],
    ['vendor', '/ˈvendə(r)/', 'n', 'người bán, nhà cung cấp', 'We work with several vendors.', 'seller, supplier',
      [['street vendor', 'người bán hàng rong'], ['approved vendor', 'nhà cung cấp được duyệt']]],
    ['distribute', '/dɪˈstrɪbjuːt/', 'v', 'phân phối, phân phát', 'We distribute our products nationwide.', 'deliver, hand out',
      [['distribute products', 'phân phối sản phẩm'], ['distribution centre', 'trung tâm phân phối']]],
    ['package', '/ˈpækɪdʒ/', 'n', 'gói hàng; gói (dịch vụ)', 'A package arrived for you.', 'parcel, bundle',
      [['deliver a package', 'giao gói hàng'], ['benefits package', 'gói phúc lợi']]],
    ['ship', '/ʃɪp/', 'v', 'gửi hàng, vận chuyển', 'We ship orders within one day.', 'send, deliver',
      [['ship an order', 'gửi đơn hàng'], ['shipping cost', 'phí vận chuyển']]],
    ['courier', '/ˈkʊriə(r)/', 'n', 'dịch vụ chuyển phát', 'The documents were sent by courier.', 'delivery service, messenger',
      [['by courier', 'bằng chuyển phát nhanh'], ['courier service', 'dịch vụ chuyển phát']]],
    ['bulk', '/bʌlk/', 'n', 'số lượng lớn', 'We buy paper in bulk.', 'large quantity',
      [['in bulk', 'với số lượng lớn'], ['bulk order', 'đơn hàng số lượng lớn']]],
    ['quote', '/kwəʊt/', 'n', 'bảng báo giá', 'Can you send me a quote?', 'estimate, price',
      [['get a quote', 'lấy báo giá'], ['price quote', 'báo giá']]],
    ['replacement', '/rɪˈpleɪsmənt/', 'n', 'sự thay thế; hàng thay thế', 'We will send a replacement immediately.', 'substitute, exchange',
      [['send a replacement', 'gửi hàng thay thế'], ['replacement part', 'linh kiện thay thế']]],
    ['damaged', '/ˈdæmɪdʒd/', 'adj', 'bị hư hỏng', 'The box arrived damaged.', 'broken, harmed',
      [['badly damaged', 'hư hỏng nặng'], ['damaged in transit', 'hư hỏng khi vận chuyển']]],
    ['exchange', '/ɪksˈtʃeɪndʒ/', 'v/n', 'đổi (hàng)', 'Can I exchange this shirt?', 'swap, trade',
      [['exchange for', 'đổi lấy'], ['exchange rate', 'tỷ giá hối đoái']]],
  ],
  contract: [
    ['clause', '/klɔːz/', 'n', 'điều khoản', 'Please read clause five carefully.', 'section, term',
      [['contract clause', 'điều khoản hợp đồng'], ['add a clause', 'thêm điều khoản']]],
    ['signature', '/ˈsɪɡnətʃə(r)/', 'n', 'chữ ký', 'We need your signature here.', 'autograph, sign-off',
      [['require a signature', 'cần chữ ký'], ['digital signature', 'chữ ký số']]],
    ['obligation', '/ˌɒblɪˈɡeɪʃn/', 'n', 'nghĩa vụ', 'We have an obligation to protect customer data.', 'duty, responsibility',
      [['legal obligation', 'nghĩa vụ pháp lý'], ['under no obligation', 'không bắt buộc']]],
    ['liability', '/ˌlaɪəˈbɪləti/', 'n', 'trách nhiệm pháp lý', 'The company accepts no liability for lost items.', 'responsibility, accountability',
      [['accept liability', 'chịu trách nhiệm'], ['liability insurance', 'bảo hiểm trách nhiệm']]],
    ['breach', '/briːtʃ/', 'n/v', 'sự vi phạm', 'This is a breach of contract.', 'violation, break',
      [['breach of contract', 'vi phạm hợp đồng'], ['security breach', 'sự cố bảo mật']]],
    ['legal', '/ˈliːɡl/', 'adj', 'hợp pháp, pháp lý', 'We need legal advice.', 'lawful, legitimate',
      [['legal advice', 'tư vấn pháp lý'], ['legal department', 'phòng pháp chế']]],
    ['lawyer', '/ˈlɔːjə(r)/', 'n', 'luật sư', 'Our lawyer checked the contract.', 'attorney, legal adviser',
      [['consult a lawyer', 'hỏi ý kiến luật sư'], ['hire a lawyer', 'thuê luật sư']]],
    ['permit', '/ˈpɜːmɪt/', 'n', 'giấy phép', 'You need a permit to park here.', 'licence, authorization',
      [['work permit', 'giấy phép lao động'], ['parking permit', 'thẻ đỗ xe']]],
    ['licence', '/ˈlaɪsns/', 'n', 'giấy phép, bằng', 'He has a driving licence.', 'permit, certificate',
      [['driving licence', 'bằng lái xe'], ['business licence', 'giấy phép kinh doanh']]],
    ['valid', '/ˈvælɪd/', 'adj', 'có hiệu lực, hợp lệ', 'This ticket is valid for one month.', 'effective, current',
      [['valid for', 'có hiệu lực trong'], ['valid ID', 'giấy tờ tùy thân hợp lệ']]],
    ['revise', '/rɪˈvaɪz/', 'v', 'sửa đổi, điều chỉnh', 'We revised the contract twice.', 'amend, modify',
      [['revise a plan', 'điều chỉnh kế hoạch'], ['revised version', 'bản đã sửa']]],
    ['draft', '/drɑːft/', 'n/v', 'bản nháp; soạn thảo', 'Please send me the first draft.', 'outline, version',
      [['first draft', 'bản nháp đầu tiên'], ['draft a contract', 'soạn thảo hợp đồng']]],
    ['violate', '/ˈvaɪəleɪt/', 'v', 'vi phạm', 'The company violated safety rules.', 'break, breach',
      [['violate a rule', 'vi phạm quy định'], ['violate an agreement', 'vi phạm thỏa thuận']]],
    ['confidential', '/ˌkɒnfɪˈdenʃl/', 'adj', 'bí mật, mật', 'This information is strictly confidential.', 'private, secret',
      [['strictly confidential', 'tuyệt mật'], ['confidential information', 'thông tin mật']]],
    ['restriction', '/rɪˈstrɪkʃn/', 'n', 'sự hạn chế', 'There are restrictions on imports.', 'limit, limitation',
      [['impose restrictions', 'áp đặt hạn chế'], ['travel restrictions', 'hạn chế đi lại']]],
  ],
};

// Chủ đề TOEIC mới
const TOEIC_NEW_TOPICS = [
  { id: 'production', name: 'Sản xuất, nhà máy', icon: '🏭', words: [
    ['manufacture', '/ˌmænjuˈfæktʃə(r)/', 'v', 'sản xuất', 'The company manufactures car parts.', 'produce, make',
      [['manufacture goods', 'sản xuất hàng hóa'], ['manufacturing plant', 'nhà máy sản xuất']]],
    ['factory', '/ˈfæktri/', 'n', 'nhà máy', 'The factory employs two thousand workers.', 'plant, mill',
      [['factory worker', 'công nhân nhà máy'], ['build a factory', 'xây nhà máy']]],
    ['plant', '/plɑːnt/', 'n', 'nhà máy', 'The new plant opened last month.', 'factory, facility',
      [['power plant', 'nhà máy điện'], ['chemical plant', 'nhà máy hóa chất']]],
    ['assembly line', '/əˈsembli laɪn/', 'n', 'dây chuyền lắp ráp', 'He works on the assembly line.', 'production line',
      [['work on an assembly line', 'làm ở dây chuyền'], ['assembly line worker', 'công nhân dây chuyền']]],
    ['produce', '/prəˈdjuːs/', 'v', 'sản xuất, tạo ra', 'The factory produces ten thousand units a day.', 'make, create',
      [['produce goods', 'sản xuất hàng hóa'], ['mass produce', 'sản xuất hàng loạt']]],
    ['output', '/ˈaʊtpʊt/', 'n', 'sản lượng', 'Output increased by ten percent.', 'production, yield',
      [['increase output', 'tăng sản lượng'], ['daily output', 'sản lượng hằng ngày']]],
    ['capacity', '/kəˈpæsəti/', 'n', 'công suất, sức chứa', 'The factory is working at full capacity.', 'ability, volume',
      [['at full capacity', 'hết công suất'], ['seating capacity', 'sức chứa chỗ ngồi']]],
    ['machinery', '/məˈʃiːnəri/', 'n', 'máy móc', 'The factory bought new machinery.', 'equipment, machines',
      [['heavy machinery', 'máy móc hạng nặng'], ['operate machinery', 'vận hành máy móc']]],
    ['operate', '/ˈɒpəreɪt/', 'v', 'vận hành, hoạt động', 'Only trained staff can operate this machine.', 'run, work',
      [['operate a machine', 'vận hành máy'], ['operating costs', 'chi phí hoạt động']]],
    ['maintenance', '/ˈmeɪntənəns/', 'n', 'sự bảo trì', 'The machine needs regular maintenance.', 'upkeep, servicing',
      [['regular maintenance', 'bảo trì định kỳ'], ['maintenance work', 'công việc bảo trì']]],
    ['repair', '/rɪˈpeə(r)/', 'v/n', 'sửa chữa', 'The technician repaired the printer.', 'fix, mend',
      [['repair work', 'công việc sửa chữa'], ['under repair', 'đang được sửa']]],
    ['inspect', '/ɪnˈspekt/', 'v', 'kiểm tra, thanh tra', 'Officials inspected the factory.', 'examine, check',
      [['inspect equipment', 'kiểm tra thiết bị'], ['safety inspection', 'kiểm tra an toàn']]],
    ['raw material', '/ˌrɔː məˈtɪəriəl/', 'n', 'nguyên liệu thô', 'The price of raw materials has risen.', 'resources, supplies',
      [['source raw materials', 'tìm nguồn nguyên liệu'], ['cost of raw materials', 'chi phí nguyên liệu']]],
    ['component', '/kəmˈpəʊnənt/', 'n', 'linh kiện, thành phần', 'We import electronic components.', 'part, element',
      [['key component', 'thành phần chính'], ['electronic component', 'linh kiện điện tử']]],
    ['automate', '/ˈɔːtəmeɪt/', 'v', 'tự động hóa', 'We automated the packing process.', 'mechanize, computerize',
      [['fully automated', 'tự động hoàn toàn'], ['automate a process', 'tự động hóa quy trình']]],
    ['facility', '/fəˈsɪləti/', 'n', 'cơ sở; tiện ích', 'The new facility opens next year.', 'building, site',
      [['production facility', 'cơ sở sản xuất'], ['sports facilities', 'tiện ích thể thao']]],
    ['safety', '/ˈseɪfti/', 'n', 'sự an toàn', 'Safety is our top priority.', 'security, protection',
      [['safety measures', 'biện pháp an toàn'], ['safety equipment', 'thiết bị bảo hộ']]],
    ['hazard', '/ˈhæzəd/', 'n', 'mối nguy hiểm', 'Wet floors are a safety hazard.', 'danger, risk',
      [['fire hazard', 'nguy cơ cháy'], ['health hazard', 'mối nguy cho sức khỏe']]],
    ['protective', '/prəˈtektɪv/', 'adj', 'bảo hộ, bảo vệ', 'Workers must wear protective clothing.', 'safety, shielding',
      [['protective clothing', 'quần áo bảo hộ'], ['protective gear', 'đồ bảo hộ']]],
    ['procedure', '/prəˈsiːdʒə(r)/', 'n', 'quy trình, thủ tục', 'Please follow the safety procedures.', 'process, method',
      [['follow a procedure', 'làm theo quy trình'], ['standard procedure', 'quy trình chuẩn']]],
    ['standard', '/ˈstændəd/', 'n', 'tiêu chuẩn', 'Our products meet international standards.', 'level, norm',
      [['meet standards', 'đạt tiêu chuẩn'], ['high standard', 'tiêu chuẩn cao']]],
    ['prototype', '/ˈprəʊtətaɪp/', 'n', 'mẫu thử nghiệm', 'The engineers built a prototype.', 'model, sample',
      [['build a prototype', 'chế tạo mẫu thử'], ['test a prototype', 'thử nghiệm mẫu']]],
    ['install', '/ɪnˈstɔːl/', 'v', 'lắp đặt, cài đặt', 'A technician will install the machine.', 'set up, fit',
      [['install equipment', 'lắp đặt thiết bị'], ['install software', 'cài đặt phần mềm']]],
    ['malfunction', '/ˌmælˈfʌŋkʃn/', 'n/v', 'sự trục trặc; hỏng hóc', 'The machine had a malfunction.', 'breakdown, fault',
      [['equipment malfunction', 'thiết bị trục trặc'], ['technical malfunction', 'lỗi kỹ thuật']]],
    ['upgrade', '/ˌʌpˈɡreɪd/', 'v/n', 'nâng cấp', 'We need to upgrade our equipment.', 'improve, update',
      [['upgrade equipment', 'nâng cấp thiết bị'], ['system upgrade', 'nâng cấp hệ thống']]],
  ]},
  { id: 'tech', name: 'Công nghệ, IT', icon: '💻', words: [
    ['software', '/ˈsɒftweə(r)/', 'n', 'phần mềm', 'We use accounting software.', 'program, application',
      [['software update', 'bản cập nhật phần mềm'], ['software developer', 'lập trình viên']]],
    ['hardware', '/ˈhɑːdweə(r)/', 'n', 'phần cứng', 'The hardware is old.', 'equipment, devices',
      [['computer hardware', 'phần cứng máy tính'], ['hardware problem', 'sự cố phần cứng']]],
    ['device', '/dɪˈvaɪs/', 'n', 'thiết bị', 'Please turn off all electronic devices.', 'gadget, machine',
      [['electronic device', 'thiết bị điện tử'], ['mobile device', 'thiết bị di động']]],
    ['network', '/ˈnetwɜːk/', 'n', 'mạng lưới, mạng máy tính', 'The office network is down.', 'system, web',
      [['computer network', 'mạng máy tính'], ['network connection', 'kết nối mạng']]],
    ['database', '/ˈdeɪtəbeɪs/', 'n', 'cơ sở dữ liệu', 'Customer details are stored in a database.', 'data bank, records',
      [['customer database', 'dữ liệu khách hàng'], ['update a database', 'cập nhật cơ sở dữ liệu']]],
    ['password', '/ˈpɑːswɜːd/', 'n', 'mật khẩu', 'Please change your password.', 'passcode, PIN',
      [['enter a password', 'nhập mật khẩu'], ['reset a password', 'đặt lại mật khẩu']]],
    ['log in', '/ˌlɒɡ ˈɪn/', 'v', 'đăng nhập', 'Please log in to your account.', 'sign in',
      [['log in to', 'đăng nhập vào'], ['login details', 'thông tin đăng nhập']]],
    ['download', '/ˌdaʊnˈləʊd/', 'v', 'tải xuống', 'You can download the form from our website.', 'save, get',
      [['download a file', 'tải tệp'], ['free download', 'tải miễn phí']]],
    ['access', '/ˈækses/', 'n/v', 'quyền truy cập; truy cập', 'Only managers have access to this room.', 'entry, admission',
      [['have access to', 'có quyền vào/truy cập'], ['access the internet', 'truy cập internet']]],
    ['backup', '/ˈbækʌp/', 'n', 'bản sao lưu', 'Always make a backup of your files.', 'copy, spare',
      [['make a backup', 'sao lưu'], ['backup copy', 'bản sao lưu']]],
    ['update', '/ˌʌpˈdeɪt/', 'v/n', 'cập nhật', 'Please update your contact details.', 'renew, refresh',
      [['update records', 'cập nhật hồ sơ'], ['latest update', 'bản cập nhật mới nhất']]],
    ['technical', '/ˈteknɪkl/', 'adj', 'thuộc về kỹ thuật', 'We had some technical problems.', 'technological, mechanical',
      [['technical support', 'hỗ trợ kỹ thuật'], ['technical problem', 'sự cố kỹ thuật']]],
    ['technician', '/tekˈnɪʃn/', 'n', 'kỹ thuật viên', 'A technician will fix your computer.', 'engineer, mechanic',
      [['call a technician', 'gọi kỹ thuật viên'], ['IT technician', 'kỹ thuật viên IT']]],
    ['troubleshoot', '/ˈtrʌblʃuːt/', 'v', 'tìm và khắc phục sự cố', 'He troubleshoots network problems.', 'fix, solve',
      [['troubleshoot a problem', 'khắc phục sự cố'], ['troubleshooting guide', 'hướng dẫn khắc phục sự cố']]],
    ['security', '/sɪˈkjʊərəti/', 'n', 'an ninh, bảo mật', 'We take data security seriously.', 'protection, safety',
      [['security system', 'hệ thống an ninh'], ['data security', 'bảo mật dữ liệu']]],
    ['website', '/ˈwebsaɪt/', 'n', 'trang web', 'Visit our website for more information.', 'site, web page',
      [['visit a website', 'truy cập trang web'], ['company website', 'trang web công ty']]],
    ['digital', '/ˈdɪdʒɪtl/', 'adj', 'kỹ thuật số', 'We send digital invoices.', 'electronic, online',
      [['digital copy', 'bản điện tử'], ['digital marketing', 'tiếp thị số']]],
    ['compatible', '/kəmˈpætəbl/', 'adj', 'tương thích', 'This software is compatible with Windows.', 'suitable, consistent',
      [['compatible with', 'tương thích với'], ['fully compatible', 'hoàn toàn tương thích']]],
    ['storage', '/ˈstɔːrɪdʒ/', 'n', 'sự lưu trữ; kho chứa', 'We need more storage space.', 'space, capacity',
      [['storage space', 'không gian lưu trữ'], ['cloud storage', 'lưu trữ đám mây']]],
    ['server', '/ˈsɜːvə(r)/', 'n', 'máy chủ', 'The server is down.', 'host, main computer',
      [['web server', 'máy chủ web'], ['server room', 'phòng máy chủ']]],
    ['connection', '/kəˈnekʃn/', 'n', 'sự kết nối', 'The internet connection is slow.', 'link, access',
      [['internet connection', 'kết nối internet'], ['lose connection', 'mất kết nối']]],
    ['application', '/ˌæplɪˈkeɪʃn/', 'n', 'ứng dụng; đơn xin', 'Download our mobile application.', 'app, program',
      [['mobile application', 'ứng dụng di động'], ['job application', 'đơn xin việc']]],
    ['user', '/ˈjuːzə(r)/', 'n', 'người dùng', 'The app has one million users.', 'customer, consumer',
      [['user name', 'tên người dùng'], ['user-friendly', 'dễ sử dụng']]],
    ['platform', '/ˈplætfɔːm/', 'n', 'nền tảng', 'We sell on several online platforms.', 'system, channel',
      [['online platform', 'nền tảng trực tuyến'], ['social media platform', 'nền tảng mạng xã hội']]],
    ['wireless', '/ˈwaɪələs/', 'adj', 'không dây', 'The hotel has free wireless internet.', 'Wi-Fi, cordless',
      [['wireless internet', 'internet không dây'], ['wireless network', 'mạng không dây']]],
  ]},
  { id: 'email', name: 'Email, thư từ', icon: '✉️', words: [
    ['attach', '/əˈtætʃ/', 'v', 'đính kèm', 'I have attached the report.', 'enclose, add',
      [['attach a file', 'đính kèm tệp'], ['please find attached', 'vui lòng xem tệp đính kèm']]],
    ['attachment', '/əˈtætʃmənt/', 'n', 'tệp đính kèm', 'Please open the attachment.', 'attached file, enclosure',
      [['email attachment', 'tệp đính kèm email'], ['open an attachment', 'mở tệp đính kèm']]],
    ['reply', '/rɪˈplaɪ/', 'v/n', 'trả lời', 'Please reply to this email.', 'respond, answer',
      [['reply to', 'trả lời (ai/cái gì)'], ['prompt reply', 'hồi âm nhanh']]],
    ['forward', '/ˈfɔːwəd/', 'v', 'chuyển tiếp', 'I will forward the email to you.', 'send on, pass on',
      [['forward an email', 'chuyển tiếp email'], ['forward to', 'chuyển tiếp cho']]],
    ['recipient', '/rɪˈsɪpiənt/', 'n', 'người nhận', 'Please check the recipient list.', 'receiver, addressee',
      [['intended recipient', 'người nhận chính thức'], ['award recipient', 'người nhận giải']]],
    ['sender', '/ˈsendə(r)/', 'n', 'người gửi', 'Return the letter to the sender.', 'writer, dispatcher',
      [['return to sender', 'trả lại người gửi'], ['sender address', 'địa chỉ người gửi']]],
    ['inquiry', '/ɪnˈkwaɪəri/', 'n', 'thư hỏi, câu hỏi', 'Thank you for your inquiry.', 'question, request',
      [['make an inquiry', 'hỏi thông tin'], ['customer inquiry', 'câu hỏi của khách hàng']]],
    ['enclose', '/ɪnˈkləʊz/', 'v', 'gửi kèm', 'I have enclosed a copy of my CV.', 'attach, include',
      [['please find enclosed', 'vui lòng xem tài liệu gửi kèm'], ['enclose a copy', 'gửi kèm bản sao']]],
    ['regarding', '/rɪˈɡɑːdɪŋ/', 'prep', 'về, liên quan đến', 'I am writing regarding your order.', 'about, concerning',
      [['regarding your inquiry', 'về câu hỏi của bạn'], ['regarding the meeting', 'về cuộc họp']]],
    ['correspondence', '/ˌkɒrəˈspɒndəns/', 'n', 'thư từ trao đổi', 'Please keep all correspondence.', 'letters, emails',
      [['business correspondence', 'thư tín thương mại'], ['previous correspondence', 'thư từ trước đó']]],
    ['notify', '/ˈnəʊtɪfaɪ/', 'v', 'thông báo', 'We will notify you by email.', 'inform, tell',
      [['notify somebody of', 'thông báo cho ai về'], ['notify immediately', 'thông báo ngay']]],
    ['acknowledge', '/əkˈnɒlɪdʒ/', 'v', 'xác nhận đã nhận; thừa nhận', 'Please acknowledge receipt of this email.', 'confirm, admit',
      [['acknowledge receipt', 'xác nhận đã nhận'], ['acknowledge a mistake', 'thừa nhận lỗi']]],
    ['request', '/rɪˈkwest/', 'n/v', 'yêu cầu', 'We received your request.', 'ask for, demand',
      [['make a request', 'đưa ra yêu cầu'], ['upon request', 'khi có yêu cầu']]],
    ['urgent', '/ˈɜːdʒənt/', 'adj', 'khẩn cấp', 'This is an urgent matter.', 'pressing, important',
      [['urgent matter', 'vấn đề khẩn'], ['urgent request', 'yêu cầu khẩn']]],
    ['appreciate', '/əˈpriːʃieɪt/', 'v', 'cảm kích, đánh giá cao', 'I appreciate your help.', 'value, be grateful for',
      [['greatly appreciate', 'vô cùng cảm kích'], ['would appreciate it if', 'sẽ rất cảm kích nếu']]],
    ['apologize', '/əˈpɒlədʒaɪz/', 'v', 'xin lỗi', 'We apologize for the delay.', 'say sorry, regret',
      [['apologize for', 'xin lỗi vì'], ['sincerely apologize', 'thành thật xin lỗi']]],
    ['inconvenience', '/ˌɪnkənˈviːniəns/', 'n', 'sự bất tiện', 'We are sorry for any inconvenience.', 'trouble, bother',
      [['cause inconvenience', 'gây bất tiện'], ['any inconvenience', 'bất kỳ sự bất tiện nào']]],
    ['reminder', '/rɪˈmaɪndə(r)/', 'n', 'lời nhắc', 'This is a reminder about the meeting tomorrow.', 'notice, prompt',
      [['send a reminder', 'gửi lời nhắc'], ['friendly reminder', 'lời nhắc nhẹ nhàng']]],
    ['follow up', '/ˌfɒləʊ ˈʌp/', 'v', 'theo dõi, liên hệ lại', 'I will follow up with the client tomorrow.', 'check on, pursue',
      [['follow up on', 'theo dõi tiếp về'], ['follow-up email', 'email liên hệ lại']]],
    ['contact', '/ˈkɒntækt/', 'v/n', 'liên lạc', 'Please contact me if you have questions.', 'reach, get in touch with',
      [['contact details', 'thông tin liên lạc'], ['get in contact with', 'liên lạc với']]],
    ['previous', '/ˈpriːviəs/', 'adj', 'trước đó', 'As I mentioned in my previous email.', 'earlier, former',
      [['previous email', 'email trước'], ['previous experience', 'kinh nghiệm trước đây']]],
    ['further', '/ˈfɜːðə(r)/', 'adj', 'thêm, hơn nữa', 'Please contact us for further information.', 'additional, more',
      [['further information', 'thêm thông tin'], ['until further notice', 'cho đến khi có thông báo mới']]],
    ['subject', '/ˈsʌbdʒɪkt/', 'n', 'chủ đề; tiêu đề', 'Please write a clear subject line.', 'topic, title',
      [['subject line', 'dòng tiêu đề'], ['subject to change', 'có thể thay đổi']]],
    ['response', '/rɪˈspɒns/', 'n', 'sự phản hồi', 'We look forward to your response.', 'reply, answer',
      [['in response to', 'để phản hồi'], ['quick response', 'phản hồi nhanh']]],
    ['recommend', '/ˌrekəˈmend/', 'v', 'đề xuất, giới thiệu', 'I highly recommend this hotel.', 'suggest, advise',
      [['highly recommend', 'rất khuyên dùng'], ['strongly recommend', 'khuyến nghị mạnh mẽ']]],
  ]},
  { id: 'events', name: 'Nhà hàng, sự kiện', icon: '🍽️', words: [
    ['cater', '/ˈkeɪtə(r)/', 'v', 'cung cấp đồ ăn (cho sự kiện)', 'A local restaurant catered the party.', 'provide food, serve',
      [['cater for', 'phục vụ, đáp ứng'], ['catering service', 'dịch vụ đặt tiệc']]],
    ['banquet', '/ˈbæŋkwɪt/', 'n', 'yến tiệc', 'The awards banquet was held at a hotel.', 'dinner party, feast',
      [['banquet hall', 'sảnh tiệc'], ['hold a banquet', 'tổ chức tiệc']]],
    ['venue', '/ˈvenjuː/', 'n', 'địa điểm (tổ chức)', 'We need a venue for the conference.', 'location, place',
      [['conference venue', 'địa điểm hội nghị'], ['book a venue', 'đặt địa điểm']]],
    ['reception', '/rɪˈsepʃn/', 'n', 'quầy lễ tân; tiệc chiêu đãi', 'Please leave your key at reception.', 'front desk, party',
      [['reception desk', 'quầy lễ tân'], ['wedding reception', 'tiệc cưới']]],
    ['host', '/həʊst/', 'v/n', 'đăng cai, tổ chức; chủ nhà', 'Our company will host the event.', 'organize, hold',
      [['host an event', 'đăng cai sự kiện'], ['host country', 'nước chủ nhà']]],
    ['guest', '/ɡest/', 'n', 'khách mời', 'We invited one hundred guests.', 'visitor, attendee',
      [['guest speaker', 'diễn giả khách mời'], ['guest list', 'danh sách khách mời']]],
    ['invitation', '/ˌɪnvɪˈteɪʃn/', 'n', 'lời mời, thiệp mời', 'Thank you for the invitation.', 'invite, request',
      [['accept an invitation', 'nhận lời mời'], ['decline an invitation', 'từ chối lời mời']]],
    ['menu', '/ˈmenjuː/', 'n', 'thực đơn', 'Could I see the menu, please?', 'list of dishes',
      [['set menu', 'thực đơn cố định'], ['on the menu', 'có trong thực đơn']]],
    ['dish', '/dɪʃ/', 'n', 'món ăn', 'This is our most popular dish.', 'meal, course',
      [['main dish', 'món chính'], ['side dish', 'món ăn kèm']]],
    ['reserve', '/rɪˈzɜːv/', 'v', 'đặt trước', 'I would like to reserve a table for four.', 'book, hold',
      [['reserve a table', 'đặt bàn'], ['reserve a seat', 'đặt chỗ ngồi']]],
    ['organize', '/ˈɔːɡənaɪz/', 'v', 'tổ chức', 'She organized the company trip.', 'arrange, plan',
      [['organize an event', 'tổ chức sự kiện'], ['well organized', 'được tổ chức tốt']]],
    ['celebrate', '/ˈselɪbreɪt/', 'v', 'kỷ niệm, ăn mừng', 'We celebrated our tenth anniversary.', 'mark, commemorate',
      [['celebrate success', 'ăn mừng thành công'], ['celebrate an anniversary', 'kỷ niệm ngày thành lập']]],
    ['anniversary', '/ˌænɪˈvɜːsəri/', 'n', 'ngày kỷ niệm', 'The company will celebrate its anniversary next week.', 'celebration, jubilee',
      [['tenth anniversary', 'kỷ niệm 10 năm'], ['wedding anniversary', 'kỷ niệm ngày cưới']]],
    ['award', '/əˈwɔːd/', 'n/v', 'giải thưởng; trao giải', 'She won an award for best employee.', 'prize, honour',
      [['win an award', 'giành giải thưởng'], ['award ceremony', 'lễ trao giải']]],
    ['ceremony', '/ˈserəməni/', 'n', 'buổi lễ', 'The opening ceremony starts at ten.', 'event, celebration',
      [['opening ceremony', 'lễ khai mạc'], ['closing ceremony', 'lễ bế mạc']]],
    ['occasion', '/əˈkeɪʒn/', 'n', 'dịp', 'This is a special occasion.', 'event, celebration',
      [['special occasion', 'dịp đặc biệt'], ['on this occasion', 'nhân dịp này']]],
    ['refreshments', '/rɪˈfreʃmənts/', 'n', 'đồ ăn nhẹ và đồ uống', 'Refreshments will be served after the talk.', 'snacks, drinks',
      [['serve refreshments', 'phục vụ đồ ăn nhẹ'], ['light refreshments', 'đồ ăn nhẹ']]],
    ['buffet', '/ˈbʊfeɪ/', 'n', 'tiệc tự chọn', 'Breakfast is a buffet.', 'self-service meal',
      [['buffet lunch', 'bữa trưa tự chọn'], ['buffet breakfast', 'bữa sáng tự chọn']]],
    ['beverage', '/ˈbevərɪdʒ/', 'n', 'đồ uống', 'Food and beverages are included.', 'drink',
      [['hot beverage', 'đồ uống nóng'], ['food and beverage', 'ăn uống (F&B)']]],
    ['chef', '/ʃef/', 'n', 'đầu bếp', 'The chef prepared a special menu.', 'cook',
      [['head chef', 'bếp trưởng'], ['pastry chef', 'thợ làm bánh']]],
    ['serve', '/sɜːv/', 'v', 'phục vụ', 'Dinner is served at seven.', 'provide, offer',
      [['serve customers', 'phục vụ khách hàng'], ['serve food', 'phục vụ đồ ăn']]],
    ['dietary', '/ˈdaɪətəri/', 'adj', 'thuộc về chế độ ăn', 'Please tell us about any dietary requirements.', 'food-related',
      [['dietary requirements', 'yêu cầu về ăn uống'], ['dietary restrictions', 'hạn chế ăn uống']]],
    ['appetizer', '/ˈæpɪtaɪzə(r)/', 'n', 'món khai vị', 'We ordered two appetizers.', 'starter',
      [['order an appetizer', 'gọi món khai vị'], ['light appetizer', 'món khai vị nhẹ']]],
    ['register', '/ˈredʒɪstə(r)/', 'v', 'đăng ký', 'Please register for the conference online.', 'sign up, enrol',
      [['register for', 'đăng ký tham gia'], ['registration form', 'mẫu đăng ký']]],
    ['attendance', '/əˈtendəns/', 'n', 'sự tham dự; số người dự', 'Attendance at the event was high.', 'presence, turnout',
      [['high attendance', 'số người tham dự đông'], ['attendance record', 'hồ sơ chuyên cần']]],
  ]},
];

TOEIC_VOCAB.forEach(t => { if (TOEIC_EXTRA[t.id]) t.words.push(...TOEIC_EXTRA[t.id]); });
TOEIC_VOCAB.push(...TOEIC_NEW_TOPICS);

// TOEIC đứng trước nên từ mới sẽ lấy từ bộ TOEIC trước.
const VOCAB = [
  ...TOEIC_VOCAB.map(t => ({ ...t, group: 'TOEIC' })),
  ...BASIC_VOCAB.map(t => ({ ...t, group: 'Cơ bản' })),
];
